In [3]:
import pandas as pd
import os 
import shutil
import openpyxl

## Read data

In [4]:
excel_file_path = 'data/progresivas.xlsx'
df = pd.read_excel(excel_file_path)
df.head()

,progresivas,ancho,largo,descripcion_formal,descripcion_personalizada,progresivas_al_reves,id_foto,isValid
0,0,4,-,-,-,11050,68,1
1,180,5,-,Alcantarilla,alcantarilla de dos ojos,10870,67,1
2,250,5,-,-,-,10800,66,1
3,500,5,-,-,-,10550,65,1
4,750,4,-,-,-,10300,64,1

In [5]:
codigo_ruta="R040516"

In [6]:
def formato_progresiva(valor_en_metros):
    km, metros = divmod(valor_en_metros, 1000)
    return f"{int(km)}+{metros:03d}"

In [10]:
df['progresivas_formateadas']=df['progresivas_al_reves'].map(formato_progresiva)

In [13]:
df.tail()

,progresivas,ancho,largo,descripcion_formal,descripcion_personalizada,progresivas_al_reves,id_foto,isValid,progresivas_formateadas
63,10500,4.2,-,Hito_kilometrico,-,550,5,1,0+550
64,10750,4.2,-,-,-,300,4,1,0+300
65,11000,4.6,-,-,-,50,3,1,0+050
66,11020,-,-,Se単al_informativa,Se単al,30,2,1,0+030
67,11050,4,10.5,Inicio,Puente,0,1,1,0+000

In [14]:
carpeta_origen="./images"

carpeta_destino="./output"

In [38]:
total_valid_values=df['isValid'].sum()
print(type(total_valid_values))

<class 'numpy.int64'>

In [42]:
contador=0

total_valid_values=df['isValid'].sum()

df['new_name']=''

for index, row in df.iterrows():
    
    if row['isValid']==1:
        image_enumerator=f'{total_valid_values-contador:02}'

        label=""

        if row['descripcion_formal']=="-":
            label="Medicion"
        else:
            label=row['descripcion_formal']

        row['new_name']=f'{image_enumerator}_{codigo_ruta}_{label}_{row["progresivas_formateadas"]}.jpg'

        ruta_origen=os.path.join(carpeta_origen, f'{row['id_foto']}.JPG')
        ruta_destino=os.path.join(carpeta_destino, row['new_name'])
        print(row['new_name'])
        shutil.copyfile(ruta_origen, ruta_destino)
        contador+=1

67_R040516_Medicion_11+050.jpg
66_R040516_Alcantarilla_10+870.jpg
65_R040516_Medicion_10+800.jpg
64_R040516_Medicion_10+550.jpg
63_R040516_Medicion_10+300.jpg
62_R040516_Hito_kilometrico_10+080.jpg
61_R040516_Medicion_10+050.jpg
60_R040516_Medicion_9+800.jpg
59_R040516_Alcantarilla_9+630.jpg
58_R040516_Medicion_9+550.jpg
57_R040516_Medicion_9+300.jpg
56_R040516_Medicion_9+050.jpg
55_R040516_Medicion_8+800.jpg
54_R040516_Medicion_8+550.jpg
53_R040516_Medicion_8+300.jpg
52_R040516_Baden_8+230.jpg
51_R040516_Hito_kilometrico_8+090.jpg
50_R040516_Medicion_8+050.jpg
49_R040516_Medicion_7+800.jpg
48_R040516_Medicion_7+550.jpg
47_R040516_Medicion_7+300.jpg
46_R040516_Alcantarilla_7+130.jpg
45_R040516_Medicion_7+050.jpg
44_R040516_Hito_kilometrico_7+020.jpg
43_R040516_Medicion_6+800.jpg
42_R040516_Medicion_6+550.jpg
41_R040516_Medicion_6+300.jpg
40_R040516_Medicion_6+050.jpg
39_R040516_Hito_kilometrico_6+020.jpg
38_R040516_Alcantarilla_5+850.jpg
37_R040516_Se単al_informativa_5+838.jpg
36_R040516_Medicion_5+800.jpg
35_R040516_Medicion_5+550.jpg
34_R040516_Medicion_5+300.jpg
33_R040516_Medicion_5+050.jpg
32_R040516_Hito_kilometrico_5+020.jpg
31_R040516_Baden_4+860.jpg
30_R040516_Medicion_4+800.jpg
29_R040516_Medicion_4+550.jpg
28_R040516_Medicion_4+300.jpg
27_R040516_Medicion_4+050.jpg
26_R040516_Hito_kilometrico_4+030.jpg
25_R040516_Medicion_3+800.jpg
24_R040516_Alcantarilla_3+600.jpg
23_R040516_Medicion_3+550.jpg
22_R040516_Medicion_3+300.jpg
21_R040516_Medicion_3+050.jpg
20_R040516_Hito_kilometrico_3+020.jpg
19_R040516_Medicion_2+800.jpg
18_R040516_Medicion_2+550.jpg
17_R040516_Baden_2+470.jpg
16_R040516_Medicion_2+300.jpg
15_R040516_Baden_2+020.jpg
14_R040516_Hito_kilometrico_1+950.jpg
13_R040516_Medicion_1+800.jpg
12_R040516_Medicion_1+550.jpg
11_R040516_Medicion_1+300.jpg
10_R040516_Alcantarilla_1+050.jpg
09_R040516_Medicion_1+050.jpg
08_R040516_Hito_kilometrico_0+910.jpg
07_R040516_Baden_0+870.jpg
06_R040516_Medicion_0+800.jpg
05_R040516_Hito_kilometrico_0+550.jpg
04_R040516_Medicion_0+300.jpg
03_R040516_Medicion_0+050.jpg
02_R040516_Se単al_informativa_0+030.jpg
01_R040516_Inicio_0+000.jpg